#EXPECTED KEYS FROM THE LLM
EXPECTED_LLM_KEYS = {"A", "A_B", "B", "A_C", "C", "D"}

#ERROR HANDLERS:

ERROR_JSON_PARSING = 1
ERROR_NOT_DICT = 2
ERROR_NUMBER_KEYS = 3
ERROR_UNKNOWN_ERROR = 4
ERROR_EMPTY_STRING = 5
ERROR_OLLAMA_NOT_RUNNING = 6

#WIDTH AND HEIGHT

FIXED_WIDTH = 1293
FIXED_HEIGHT = 895

#EDGE AND NODES COLORS

EDGE_HIGHLIGHT = "#40e0d0"
EDGE_EXPANDABLE = "#ce5c1e"
EDGE_NORMAL = "black"

NODE_DEFAULT = "skyblue"
NODE_LOCKED = "Gray"
NODE_START_POSITION = "Green"
NODE_SELECT = "Orange"

# TEXT COLOR

TEXT_NORMAL = "black"
TEXT_ERROR = "red"
TEXT_SUCCESS = "#355E3B" #Dark Green

TEXT_BACKGROUND_NORMAL = "white" #WHITE
TEXT_BACKGROUND_ALTERNATE = "#B0B0B0" #LIGHT GRAY

