# Form implementation generated from reading ui file '.\Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StoryXpander(object):
    def setupUi(self, StoryXpander):
        StoryXpander.setObjectName("StoryXpander")
        StoryXpander.resize(1293, 749)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StoryXpander.sizePolicy().hasHeightForWidth())
        StoryXpander.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=StoryXpander)
        self.centralwidget.setObjectName("centralwidget")
        self.nodes_frames = QtWidgets.QFrame(parent=self.centralwidget)
        self.nodes_frames.setGeometry(QtCore.QRect(20, 20, 1051, 501))
        self.nodes_frames.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.nodes_frames.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.nodes_frames.setObjectName("nodes_frames")
        self.btn_expand = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_expand.setGeometry(QtCore.QRect(1100, 250, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.btn_expand.setFont(font)
        self.btn_expand.setObjectName("btn_expand")
        self.btn_export = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_export.setGeometry(QtCore.QRect(1100, 470, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.btn_export.setFont(font)
        self.btn_export.setObjectName("btn_export")
        self.expand_nodes_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.expand_nodes_list.setGeometry(QtCore.QRect(1100, 20, 171, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expand_nodes_list.setFont(font)
        self.expand_nodes_list.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.expand_nodes_list.setAutoFillBackground(False)
        self.expand_nodes_list.setObjectName("expand_nodes_list")
        self.information_box = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.information_box.setGeometry(QtCore.QRect(20, 550, 1251, 131))
        self.information_box.setReadOnly(True)
        self.information_box.setObjectName("information_box")
        StoryXpander.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StoryXpander)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1293, 22))
        self.menubar.setObjectName("menubar")
        StoryXpander.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StoryXpander)
        self.statusbar.setObjectName("statusbar")
        StoryXpander.setStatusBar(self.statusbar)

        self.retranslateUi(StoryXpander)
        QtCore.QMetaObject.connectSlotsByName(StoryXpander)

    def retranslateUi(self, StoryXpander):
        _translate = QtCore.QCoreApplication.translate
        StoryXpander.setWindowTitle(_translate("StoryXpander", "StoryXPander"))
        self.btn_expand.setText(_translate("StoryXpander", "Expand Nodes"))
        self.btn_export.setText(_translate("StoryXpander", "Export to Twine"))
